language: python
python:
- '2.7'
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_6978f21ad9c7_key -iv $encrypted_6978f21ad9c7_iv
- in id_ed25519.enc -out /mnt/c/Users/ASUS/.ssh/id_ed25519 -d
- chmod 400 /mnt/c/Users/ASUS/.ssh/id_ed25519

install:
- pip install ansible